name: Build and deploy Next.js app to CloudFront

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy to CloudFront
    runs-on: ubuntu-latest
    env:
      BUCKET: www.chisomdevopsbyexample.io
      DIST: build
      REGION: eu-north-1
      DIST_ID: E2ZCFKHSDZVVSP

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Install dependencies
        run: npm ci

      - name: Build Static Website
        run: npm run build

      - name: Sync files to S3
        run: aws s3 sync --delete ${{ env.DIST }} s3://${{ env.BUCKET }}

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.DIST_ID }} \
            --paths "/*"

      - name: Set build status output
        id: set_output
        run: echo "build_status=success" >> "$GITHUB_OUTPUT"

      - name: Show build status
        run: echo "The build status was ${{ steps.set_output.outputs.build_status }}"
